# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for epy_papers: portable onedir build.

from pathlib import Path as _Path
import pypandoc
from PyInstaller.utils.hooks import (
    collect_data_files,
    collect_dynamic_libs,
    collect_submodules,
)

# Icon: generated by `installer/make_icon.py` into assets_build/ (run in CI
# before the build); the tracked epy_papers.ico is used directly.
_ICON_PATH = _Path("assets_build/epy_papers.ico")
_ICON = str(_ICON_PATH) if _ICON_PATH.exists() else None

datas = []
datas += collect_data_files("pypandoc", include_py_files=False)

_ASSETS = _Path("src/epy_papers/assets")
datas += [
    (str(p), str(_Path("epy_papers") / p.relative_to("src/epy_papers").parent))
    for p in _ASSETS.rglob("*")
    if p.is_file() and p.suffix != ".py"
]

_DATA = _Path("src/epy_papers/data")
datas += [
    (str(p), str(_Path("epy_papers") / p.relative_to("src/epy_papers").parent))
    for p in _DATA.rglob("*")
    if p.is_file() and p.suffix != ".py"
]

binaries = []
binaries += collect_dynamic_libs("pypandoc")
_pandoc = pypandoc.get_pandoc_path()
# On Windows, pypandoc-binary ships pandoc.exe; on Linux/macOS it ships
# a plain `pandoc` binary.  Append .exe only on Windows so the spec
# works unmodified on both platforms.
import sys as _sys
if _sys.platform == "win32" and not _pandoc.lower().endswith(".exe"):
    _pandoc += ".exe"
binaries.append((_pandoc, "pypandoc/files"))

hiddenimports = collect_submodules("pypandoc") + [
    "epy_papers.assets",
    "epy_papers.assets.branding",
    "epy_papers.assets.csl",
    "epy_papers.assets.latex",
    "epy_papers.assets.templates",
    "epy_papers.assets.reference_docx",
    "epy_papers.assets.themes",
    "epy_papers.assets.mathjax",
    "epy_papers.data",
    "PIL",
    "PIL.Image",
    "yaml",
]

a = Analysis(
    ["src/epy_papers/__main__.py"],
    pathex=["src"],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter", "test", "unittest",
        "PyQt5", "PyQt6",
        "matplotlib", "pandas", "numpy",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz, a.scripts, [],
    exclude_binaries=True,
    name="epy_papers",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    icon=_ICON,
)

coll = COLLECT(
    exe, a.binaries, a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="epy_papers",
)
