"""Submission reference DOCX.

Generated by ``src/epy_papers/_core/_packaging/tools/make_reference_docx.py``.

Pandoc copies its paragraph and character styles into every DOCX draft so the
manuscript inherits the universal submission look (Times New Roman 12 pt,
double spaced, US Letter, 1-inch margins).
"""
